FROM golang:1.11-alpine3.8

ENV APP_HOME=/home/rangda

COPY . $APP_HOME

WORKDIR $APP_HOME

RUN apk update && apk add git gcc musl-dev make

RUN go mod download
RUN go mod verify
RUN make build

EXPOSE 8080

ENTRYPOINT ["bin/app"]
